name: Update Gist

on:
  push:
    branches: master

    workflow_dispatch:

  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js  --unhandled-rejections=strict
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 97235bfdaff5239f3d81ef60275bc4f8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
